##git clone

	git clone https://github.com/SuperMedIntel/Medical-SAM2.git

云服务器git clone可能出现链接超时

可以这样

	git clone https:xxx

加上一个gitclone.com的镜像

#搭建环境

	conda env create -f environment.yml

#下载权重

	bash download_ckpts.sh

#下载2D数据集

Download pre-processed REFUGE datase

	wget https://huggingface.co/datasets/jiayuanz3/REFUGE/resolve/main/REFUGE.zip

	unzip REFUGE.zip

这个也经常链接不上，可以
	
1、下载到本地,再上传 

	网站：https://huggingface.co/datasets/jiayuanz3/REFUGE/resolve/main/REFUGE.zip


#跑训练

	 python train_2d.py -net sam2 -exp_name REFUGE_MedSAM2 -vis 1 -sam_ckpt ./checkpoints/sam2_hiera_small.pt -sam_config sam2_hiera_s -image_size 1024 -out_size 1024 -b 4 -val_freq 1 -dataset REFUGE -data_path ./data/REFUGE

此时会：

	UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.


检查CUDA的能力版本

	 python -c "from torch import cuda; print(cuda.get_device_capability())"

本服务器的是-7.0

此外还有一个报错是

	INFO:root:Namespace(net='sam2', encoder='vit_b', exp_name='REFUGE_MedSAM2', vis=True, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='REFUGE', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=4, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/REFUGE', path_helper={'prefix': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31', 'ckpt_path': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31/Model', 'log_path': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31/Log', 'sample_path': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31/Samples'})

	Namespace(net='sam2', encoder='vit_b', exp_name='REFUGE_MedSAM2', vis=True, train_vis=False, prompt='bbox', prompt_freq=2, pretrain=None, val_freq=1, gpu=True, gpu_device=0, image_size=1024, out_size=1024, distributed='none', dataset='REFUGE', sam_ckpt='./checkpoints/sam2_hiera_small.pt', sam_config='sam2_hiera_s', video_length=2, b=4, lr=0.0001, weights=0, multimask_output=1, memory_bank_size=16, data_path='./data/REFUGE', path_helper={'prefix': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31', 'ckpt_path': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31/Model', 'log_path': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31/Log', 'sample_path': 'logs/REFUGE_MedSAM2_2024_11_30_02_23_31/Samples'})
	Traceback (most recent call last):                                                 
	  File "/root/zjz-医疗影像大模型/Medical-SAM2/train_2d.py", line 127, in <module>
	    main()
	  File "/root/zjz-医疗影像大模型/Medical-SAM2/train_2d.py", line 100, in main
	    tol, (eiou, edice) = function.validation_sam(args, nice_test_loader, epoch, net, writer)
	                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/root/zjz-医疗影像大模型/Medical-SAM2/func_2d/function.py", line 335, in validation_sam
	    vision_feats_temp = vision_feats[-1].permute(1, 0, 2).view(B, -1, 64, 64) 
	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

这个把view改成reshape就行了